@IES-PRC/pack.pck
@IES-PRC/pkg_x_file.pck
@IES-PRC/pkg_x_r.pck
@IES-PRC/pkg_x_s.pck
@IES-PRC/pkg_x_status_r.pck
@IES-PRC/proc_sql_register.prc
@IES-PRC/proc_add_resp_queue.prc
@IES-PRC/proc_add_send_list.prc
@IES-PRC/proc_deal_doc_exch_recv_file.prc
@IES-PRC/proc_deal_doc_exch_recv_fileex.prc
@IES-PRC/proc_deal_doc_exch_recv_status.prc
@IES-PRC/proc_deal_doc_exch_recv_pack.prc
@IES-PRC/proc_del_send_list.prc
@IES-PRC/proc_ies_initialize.prc
@IES-PRC/proc_set_resp_queue_status.prc
@IES-PRC/proc_set_send_status.prc
