@EVS-PRC1/pkg_basic.pck
@EVS-PRC1/pkg_file0.pck
@EVS-PRC1/pkg_lock.pck
@EVS-PRC1/pkg_exch_mysite.pck
@EVS-PRC1/pkg_exch_to_site.pck
@EVS-PRC1/pkg_exch_to_site_er.pck
@EVS-PRC1/pkg_exch_send.pck
@EVS-PRC1/pkg_proxy.pck
@EVS-PRC1/pkg_client.pck
@EVS-PRC1/pkg_info_template_pbl.pck
@EVS-PRC1/pkg_qp_verify.pck
@EVS-PRC1/pkg_file_download.pck
@EVS-PRC1/pkg_sys_config.pck
@EVS-PRC1/pkg_sys_queue1.pck
@EVS-PRC1/pkg_info_admin_passwd.pck
@EVS-PRC1/pkg_info_admin5.pck
@EVS-PRC1/pkg_info_admin6.pck
@EVS-PRC1/pkg_info_admin.pck
@EVS-PRC1/pkg_info_register_kind_pbl.pck
@EVS-PRC1/pkg_info_register_pbl.pck
@EVS-PRC1/pkg_info_org.pck
@EVS-PRC1/pkg_info_org2.pck
@EVS-PRC1/pkg_info_user.pck
@EVS-PRC1/pkg_info_register.pck
@EVS-PRC1/pkg_info_register_kind.pck
@EVS-PRC1/pkg_info_template_queue.pck
@EVS-PRC1/pkg_info_template_er_bind.pck
@EVS-PRC1/pkg_info_template_er_tfile.pck
@EVS-PRC1/pkg_info_template_er_ywcode.pck
@EVS-PRC1/pkg_info_template.pck
@EVS-PRC1/pkg_info_template_enable.pck
@EVS-PRC1/pkg_info_template_list.pck
@EVS-PRC1/pkg_info_template_seal.pck
@EVS-PRC1/pkg_info_template_hfile.pck
@EVS-PRC1/pkg_info_admin6_auth.pck
@EVS-PRC1/pkg_info_admin6_auth_kind.pck
@EVS-PRC1/pkg_info_app.pck
@EVS-PRC1/pkg_yz_pz_pbl.pck
@EVS-PRC1/pkg_qf_pbl.pck
@EVS-PRC1/pkg_qf_config.pck
@EVS-PRC1/pkg_qf_book.pck
@EVS-PRC1/pkg_qf_book_send.pck
@EVS-PRC1/pkg_qf_queue.pck
@EVS-PRC1/pkg_yz_first.pck
@EVS-PRC1/pkg_yz_pz_queue.pck
@EVS-PRC1/pkg_yz_pz_config.pck
@EVS-PRC1/pkg_yz_pz.pck
@EVS-PRC1/pkg_yz_sq_reply_queue2.pck
@EVS-PRC1/pkg_yz_sq_reply_queue1.pck
@EVS-PRC1/pkg_yz_sq_er.pck
@EVS-PRC1/pkg_yz_sq_config.pck
@EVS-PRC1/pkg_yz_sq.pck
@EVS-PRC1/pkg_yz_sq_reply.pck
@EVS-PRC1/pkg_yz_sq_com.pck
@EVS-PRC1/pkg_sq_first.pck
@EVS-PRC1/pkg_sq_dzcom.pck
@EVS-PRC1/pkg_sq_book_pz.pck
@EVS-PRC1/pkg_sq_book.pck
@EVS-PRC1/pkg_sq_er.pck
@EVS-PRC1/pkg_sq_pz.pck
@EVS-PRC1/pkg_qf_book_doobj.pck
@EVS-PRC1/pkg_qf_toapp_queue.pck
@EVS-PRC1/pkg_qf_book_toapp.pck
@EVS-PRC1/pkg_qf_first.pck
@EVS-PRC1/pkg_qf_book_er.pck
@EVS-PRC1/pkg_qf_book_task.pck
@EVS-PRC1/pkg_qf_batch.pck
@EVS-PRC1/pkg_qf_apply.pck
@EVS-PRC1/pkg_qf_apply_er.pck
@EVS-PRC1/pkg_qf_notice.pck
@EVS-PRC1/pkg_qf2_com.pck
@EVS-PRC1/pkg_qf2_task.pck
@EVS-PRC1/pkg_qf2_er.pck
@EVS-PRC1/pkg_platform_er.pck
@EVS-PRC1/pkg_platform_job.pck
@EVS-PRC1/pkg_op_websrv.pck
@EVS-PRC1/proc_getsyscode.prc
@EVS-PRC1/proc_login.prc
@EVS-PRC1/exchmysite_get.prc
@EVS-PRC1/opq1_qfsend.prc
@EVS-PRC1/opq1_qryqfdata.prc
@EVS-PRC1/opq1_qryqueue.prc
@EVS-PRC1/opq2_fsresult.prc
@EVS-PRC1/opq2_qryfsdata.prc
@EVS-PRC1/opq2_qryqueue.prc
@EVS-PRC1/opsq_book2queue.prc
@EVS-PRC1/opsq_book2queue_err.prc
@EVS-PRC1/opsq_book2queue_finish.prc
@EVS-PRC1/opsys2_tempqueueset.prc
@EVS-PRC1/optempl_book1oper.prc
@EVS-PRC1/optempl_book1save.prc
@EVS-PRC1/optempl_book1task.prc
@EVS-PRC1/optempl_qryinfoauto.prc
@EVS-PRC1/optempl_qryinfobook1.prc
@EVS-PRC1/opwebsrv_formoper.prc
@EVS-PRC1/opwebsrv_gettmppath.prc
@EVS-PRC1/opwebsrv_tmpfileoper.prc
@EVS-PRC1/opwebsrv_urioper.prc
@EVS-PRC1/qpsys2_delfilequeue.prc
@EVS-PRC1/qpsys2_getproxy.prc
@EVS-PRC1/qpsys2_tempqueue.prc
@EVS-PRC1/sysconfig_configinit.prc
@EVS-PRC1/sysconfig_getconfigs.prc
@EVS-PRC1/sysqueue1_getinfo.prc
@EVS-PRC1/sysqueue1_save.prc

@EVS-PRC2/pc_data_deal.prc


-- DIR *.* /B >LIST.TXT
