-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-- 前台请求用到的存储过程
truncate table info_deal;

-- 登录/系统设置/公共
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('getClientVer'           ,'getClientVer'             ,'1','call pkg_client.p_getversion(:i_forminfo, :o_info1, :o_code, :o_msg)'                                            ,'查询客户端版本');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('logininfo'              ,'logininfo'                ,'1','call proc_login(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                                ,'系统登录');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('sysInitService'         ,'getSysConfig'             ,'1','call pkg_sys_config.p_get(:i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                                   ,'TDS系统设置/获取参数');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('sysInitService'         ,'saveConfig_Proxy'         ,'1','call pkg_sys_config.p_set(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                      ,'TDS系统设置/设置保存');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('sysInitService'         ,'regSysExchData_Proxy'     ,'1','call pkg_sys_config.p_set(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                      ,'TDS系统设置/系统注册');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('sysInitService'         ,'lockStatusService'        ,'1','call pkg_lock.p_proxy(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                    ,'需加解锁操作的业务');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('proxyservice'           ,'saveSysLisence'           ,'1','call pkg_sys_config.p_register(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                           ,'保存注册码');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'downloadfile'             ,'2','call pkg_file_download.p_main(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_info2, :o_code, :o_msg)'        ,'通用文件下载方法');
-- 系统参数维护/管理员(操作员)管理
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'queryAdminPageList'       ,'1','call pkg_info_admin.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                  ,'系统参数维护/管理员管理(操作员管理)/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'operSysAdmin'             ,'1','call pkg_info_admin5.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'系统参数维护/管理员管理/增删改');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'operSysOper'              ,'1','call pkg_info_admin6.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'系统参数维护/操作员管理/增删改');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'resetUserPwd'             ,'1','call pkg_info_admin_passwd.p_reset(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                       ,'系统参数维护/管理员(操作员)管理/重置密码');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'modifyUserPwd'            ,'1','call pkg_info_admin_passwd.p_set(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                         ,'系统参数维护/我的用户信息/修改密码');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'getUserInfo'              ,'1','call pkg_info_admin.p_getinfo(:i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                               ,'系统参数维护/我的用户信息/查询用户信息');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'operUserInfo'             ,'1','call pkg_info_admin.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                               ,'系统参数维护/我的用户信息/修改用户信息');
-- 系统参数维护/签发对象分类  
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'firstLoadTree'            ,'1','call pkg_info_register_kind.p_gettree_first(:i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                 ,'系统参数维护/签发对象分类/单位(用户)分类/树根节点');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'buildKindTree'            ,'1','call pkg_info_register_kind.p_gettree_pbl(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'      ,'系统参数维护/签发对象分类(开户注册管理)/单位(用户)分类/树叶子节点');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'operKindInfo'             ,'1','call pkg_info_register_kind.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                       ,'系统参数维护/签发对象分类/单位(用户)分类/增删改');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'getSort'                  ,'1','call pkg_info_register_kind.p_getsort_pbl(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'      ,'系统参数维护/签发对象分类(开户注册管理)/获取排序号');
-- 系统参数维护/归主凭证参数维护  
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'queryTmplPageList'        ,'1','call pkg_info_template_list.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'          ,'系统参数维护/归主凭证参数维护/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'downCard'                 ,'2','call pkg_info_template.p_downcard(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_info2, :o_code, :o_msg)'    ,'系统参数维护/归主凭证参数维护/模板导出');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'useTemplateOrNot_batload' ,'2','call pkg_info_template.p_downcard(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_info2, :o_code, :o_msg)'    ,'系统参数维护/归主凭证参数维护/模板导出');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'useTemplateOrNot_proxy'   ,'1','call pkg_info_template_enable.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'           ,'系统参数维护/归主凭证参数维护/启用停用');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'updateCardSort'           ,'1','call pkg_info_template_list.p_sort(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                       ,'系统参数维护/归主凭证参数维护/修改排序');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'getBlankParamTableData'   ,'1','call pkg_info_template.p_getinfo(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'               ,'系统参数维护/归主凭证参数维护/参数维护/印制参数查询');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'setBlankParamTableData'   ,'1','call pkg_info_template.p_save(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                            ,'系统参数维护/归主凭证参数维护/参数维护/印制参数保存');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'getSignParamTableData'    ,'1','call pkg_info_template.p_getinfo(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'               ,'系统参数维护/归主凭证参数维护/参数维护/签发参数查询');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'setSignParamTableData'    ,'1','call pkg_info_template.p_save(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                            ,'系统参数维护/归主凭证参数维护/参数维护/签发参数保存');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'getSpecialParamTableData' ,'1','call pkg_info_template.p_prvdata_get(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'           ,'系统参数维护/归主凭证参数维护/参数维护/印制私有参数获取');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'setSpecialParamTableData' ,'1','call pkg_info_template.p_prvdata_set(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                     ,'系统参数维护/归主凭证参数维护/参数维护/印制私有参数保存');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'firstLoadTree'            ,'1','call pkg_info_template.p_getkind_first(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'         ,'系统参数维护/归主凭证参数维护/参数维护/签发分类/根节点');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'loadTypeTree'             ,'1','call pkg_info_template.p_getkind(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'               ,'系统参数维护/归主凭证参数维护/参数维护/签发分类/叶子节点');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'loadBlankSealDataTab'     ,'1','call pkg_info_template_seal.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'          ,'系统参数维护/归主凭证参数维护/参数维护/印制印章列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'loadSealDataTab'          ,'1','call pkg_info_template_seal.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'          ,'系统参数维护/归主凭证参数维护/参数维护/签发印章列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'addTmplSeal'              ,'1','call pkg_info_template_seal.p_add(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                        ,'系统参数维护/归主凭证参数维护/参数维护/印制(签发)印章/导入');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'deleteSeals'              ,'1','call pkg_info_template_seal.p_del(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                        ,'系统参数维护/归主凭证参数维护/参数维护/印制(签发)印章/取消');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'getBlankSealInfo'         ,'1','call pkg_info_template_seal.p_getinfo(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'          ,'系统参数维护/归主凭证参数维护/参数维护/查询印制印章信息');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'getSignSealInfo'          ,'1','call pkg_info_template_seal.p_getinfo(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'          ,'系统参数维护/归主凭证参数维护/参数维护/查询签发印章信息');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'updateBlankPassword'      ,'1','call pkg_info_template_seal.p_pin_upd(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                    ,'系统参数维护/归主凭证参数维护/参数维护/修改印制印章PIN码');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'updateSignPassword'       ,'1','call pkg_info_template_seal.p_pin_upd(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                    ,'系统参数维护/归主凭证参数维护/参数维护/修改签发印章PIN码');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'getSignApplyTmplData'     ,'1','call pkg_info_template_hfile.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'         ,'系统参数维护/归主凭证参数维护/参数维护/查询签发申领模板');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'importReplyTmpl'          ,'4','call pkg_info_template_hfile.p_add(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'             ,'系统参数维护/归主凭证参数维护/参数维护/导入签发申领模板');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('templateService'        ,'deleteReplyTmpl'          ,'1','call pkg_info_template_hfile.p_del(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                       ,'系统参数维护/归主凭证参数维护/参数维护/删除签发申领模板');

-- 系统参数维护/入账凭证参数维护
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'queryEntryTmplPageList'   ,'1','call pkg_info_template_list.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'          ,'系统参数维护/入账凭证参数维护/模板列表');

-- 绑定单位管理
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'queryAuthDeptPageList'    ,'1','call pkg_info_org2.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'          ,'系统参数维护/入账凭证参数维护/单位列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'sendAuthDeptData'         ,'1','call pkg_info_org2.p_sendselect(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'       ,'系统参数维护/入账凭证参数维护/发送数据');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'sendAllAuthDeptData'      ,'1','call pkg_info_org2.p_sendall(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                    ,'系统参数维护/入账凭证参数维护/全部发送');

-- 系统参数维护/操作员印签授权
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'loadUserTree'             ,'1','call pkg_info_admin6_auth.p_getusers(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'           ,'系统参数维护/操作员授权/用户树');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'queryAuthTypeList'        ,'1','call pkg_info_admin6_auth.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'            ,'系统参数维护/操作员授权/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'queryOperAuthList'        ,'1','call pkg_info_admin6_auth.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'            ,'系统参数维护/操作员授权/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'saveOperAuth'             ,'1','call pkg_info_admin6_auth.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                         ,'系统参数维护/操作员授权/授权确认');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'firstLoadTree'            ,'1','call pkg_info_admin6_auth_kind.p_getkind_first(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)' ,'系统参数维护/操作员授权/签发对象/根节点');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'loadTypeTree'             ,'1','call pkg_info_admin6_auth_kind.p_getkind(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'       ,'系统参数维护/操作员授权/签发对象/叶子节点');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'sureSelectTypeTree'       ,'1','call pkg_info_admin6_auth_kind.p_save(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                    ,'系统参数维护/操作员授权/签发对象保存');
-- 系统参数维护/申领应用维护
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'queryReqAppPageList'      ,'1','call pkg_info_app.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'系统参数维护/申领应用维护/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'operReqAppInfo'           ,'1','call pkg_info_app.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                 ,'系统参数维护/申领应用维护/增删改');
-- 系统参数维护/开户注册管理
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'firstLoadKindTree'        ,'1','call pkg_info_register.p_gettree_first(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'         ,'系统参数维护/开户注册管理/单位(用户)分类/树根节点');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'moveNodeData'             ,'1','call pkg_info_register.p_move(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                            ,'开户注册管理/单位(用户)开户管理/单位(用户)/移动');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'downExampleFile'          ,'2','call pkg_info_register.p_getexfile(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_info2, :o_code, :o_msg)'   ,'开户注册管理/单位(用户)开户管理/单位(用户)/批量导入/下载示例');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'queryDeptRegList'         ,'1','call pkg_info_org.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'开户注册管理/单位开户管理/单位/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'checkComCode'             ,'1','call pkg_info_org.p_ins_check(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                            ,'开户注册管理/单位开户管理/单位/增加检查');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'operDeptRegister'         ,'1','call pkg_info_org.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                       ,'开户注册管理/单位开户管理/单位/增删');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'updateDeptRegister'       ,'1','call pkg_info_org.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                       ,'开户注册管理/单位开户管理/单位/修改');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'operBatchDeptExcelData'   ,'1','call pkg_info_org.p_ins_batch(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                            ,'开户注册管理/单位开户管理/单位/批量导入(Excel)');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'operBatchDeptRegister'    ,'1','call pkg_info_org.p_ins_batch(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                            ,'开户注册管理/单位开户管理/单位/批量导入(TXT)');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'printDeptDataToExcel'     ,'1','call pkg_info_org.p_getlist2(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                   ,'开户注册管理/单位开户管理/单位/打印');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'exportDeptDataToExcel'    ,'1','call pkg_info_org.p_getlist2(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                   ,'开户注册管理/单位开户管理/单位/导出');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'queryUserRegList'         ,'1','call pkg_info_user.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                   ,'开户注册管理/用户开户管理/用户/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'checkIdCard'              ,'1','call pkg_info_user.p_ins_check(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                           ,'开户注册管理/用户开户管理/用户/增加检查');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'operUserRegister'         ,'1','call pkg_info_user.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                      ,'开户注册管理/用户开户管理/用户/增删');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'updateUserRegister'       ,'1','call pkg_info_user.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                      ,'开户注册管理/用户开户管理/用户/修改');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'operBatchUserExcelData'   ,'1','call pkg_info_user.p_ins_batch(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                           ,'开户注册管理/用户开户管理/用户/批量导入(Excel)');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'operBatchUserRegister'    ,'1','call pkg_info_user.p_ins_batch(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                           ,'开户注册管理/用户开户管理/用户/批量导入(TXT)');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'printUserDataToExcel'     ,'1','call pkg_info_user.p_getlist2(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                  ,'开户注册管理/用户开户管理/用户/打印');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('registerServiceImpl'    ,'exportUserDataToExcel'    ,'1','call pkg_info_user.p_getlist2(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                  ,'开户注册管理/用户开户管理/用户/导出');
-- 凭证签发办理
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('mixtureServiceImpl'     ,'queryPageList'            ,'1','call pkg_qf_first.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'凭证签发办理/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('noticeService'          ,'getStatusList'            ,'1','call pkg_qf_notice.p_getstatus(:i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                              ,'凭证签发办理/通知办理/办理状态');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('noticeService'          ,'buildNoteTypeTree'        ,'1','call pkg_qf_notice.p_getkind(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                   ,'凭证签发办理/通知办理/单位用户树');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('noticeService'          ,'queryNoticeRelatePageList','1','call pkg_qf_notice.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                   ,'凭证签发办理/通知办理/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('noticeService'          ,'queryNoteTmplList'        ,'1','call pkg_qf_notice.p_gethfile(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                  ,'凭证签发办理/通知办理/查询申领模板集合');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('noticeService'          ,'sendNotice'               ,'1','call pkg_qf_notice.p_send(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                ,'凭证签发办理/通知办理/发送申领通知');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('noticeService'          ,'queryRequiredFile'        ,'1','call pkg_qf_notice.p_gethfile(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                  ,'凭证签发办理/通知办理/查看申请表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'getStatusList'            ,'1','call pkg_qf_book.p_getstatuscode(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'               ,'凭证签发办理/签发办理/办理状态');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'buildObjectTypeTree'      ,'1','call pkg_qf_book_doobj.p_getkind(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'               ,'凭证签发办理/签发办理/单位用户树');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'queryTaskDealPageList'    ,'1','call pkg_qf_book.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                     ,'凭证签发办理/签发办理/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'getCertOpenInfo'          ,'2','call pkg_qf_book.p_getinfo(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_info2, :o_code, :o_msg)'           ,'凭证签发办理/签发办理/查看签发件');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'getCommSignStrage'        ,'1','call pkg_qf_config.p_getinfo(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                   ,'凭证签发办理/签发办理/签发策略查询');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'setCommSignStrage'        ,'1','call pkg_qf_config.p_save(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                ,'凭证签发办理/签发办理/签发策略保存');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'queryViewFile'            ,'2','call pkg_qf_apply.p_getfiles(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_info2, :o_code, :o_msg)'         ,'凭证签发办理/签发办理/查看申请表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'getDealTypeInfo'          ,'1','call pkg_qf_book_task.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                ,'凭证签发办理/签发办理/自动签发业务');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'loadLocalRegisterDataTab' ,'1','call pkg_qf_book_doobj.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'               ,'凭证签发办理/签发办理/签发对象查询');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'operRecvObjInfo'          ,'1','call pkg_qf_book.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                  ,'凭证签发办理/签发办理/增加签发');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'getFixedLabelStamp'       ,'1','call pkg_qf_book.p_getsealinfo(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                 ,'凭证签发办理/签发办理/签发印章查询');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'changeDestObj'            ,'1','call pkg_qf_book.p_upd_backtype(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                          ,'凭证签发办理/签发办理/接收对象设置');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'queryExchStatus'          ,'1','call pkg_qf_book_send.p_getsendstatus(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'          ,'凭证签发办理/签发办理/获取交换状态');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'getSignTypeData'          ,'1','call pkg_qf_batch.p_qfoper(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                     ,'凭证签发办理/签发办理/批量签发/签发类型');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'doneBatchImport'          ,'3','call pkg_qf_batch.p_add(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                  ,'凭证签发办理/签发办理/批量签发/签发保存');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'getIssueViewData'         ,'1','call pkg_qf_batch.p_getviewinfo(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                ,'凭证签发办理/签发办理/批量签发/签发预览');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedDao'          ,'saveBillContent'          ,'3','call pkg_qf_book.p_save(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                  ,'凭证签发办理/签发办理/签发保存');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedDao'          ,'issueProof'               ,'3','call pkg_qf_book_send.p_send(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                             ,'凭证签发办理/签发办理/签发发送');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedDao'          ,'opggs_book3return'        ,'1','call pkg_qf_book_send.p_return(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                           ,'凭证签发办理/签发办理/申请拒签');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'getWeAppPageList'         ,'1','call pkg_qf_book_toapp.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'               ,'凭证签发办理/签发办理/查询应用列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commIssuedService'      ,'getselectObjIds'          ,'1','call pkg_qf_book.p_getselectobjids(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'             ,'凭证签发办理/签发办理/检查单位、用户是否已签发');

-- 空白凭证印制
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('blankServiceImpl'       ,'queryPageList'            ,'1','call pkg_yz_first.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'空白凭证印制/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commPrintedService'     ,'getSettleInfo'            ,'1','call pkg_yz_pz_config.p_get(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'空白凭证印制/印制策略/获取库存');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commPrintedService'     ,'settleInfo'               ,'1','call pkg_yz_pz_config.p_set(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                              ,'空白凭证印制/印制策略/保存库存');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commPrintedService'     ,'queryPageList'            ,'2','call pkg_yz_pz.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_info2, :o_code, :o_msg)'             ,'空白凭证印制/空白凭证印制办理/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commPrintedService'     ,'getPageOpenInfo'          ,'2','call pkg_yz_pz.p_getinfo(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_info2, :o_code, :o_msg)'             ,'空白凭证印制/空白凭证印制办理/打开凭证');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commPrintedService'     ,'operProofInfo'            ,'2','call pkg_yz_pz.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_info2, :o_code, :o_msg)'                ,'空白凭证印制/空白凭证印制办理/删除凭证');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commPrintedService'     ,'createProofFileInfo'      ,'3','call pkg_yz_pz.p_file_add(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                ,'空白凭证印制/空白凭证印制办理/手工增加');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('commPrintedService'     ,'rptDeleteProof'           ,'1','call pkg_yz_pz.p_err(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                     ,'空白凭证印制/空白凭证印制办理/手工增加');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billAlterServiceImpl'   ,'queryPageList'            ,'1','call pkg_yz_sq.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                       ,'空白凭证印制/凭证申领分配办理/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billAlterServiceImpl'   ,'getSettleInfo'            ,'1','call pkg_yz_sq_config.p_get(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'空白凭证印制/凭证申领分配办理/获取策略');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billAlterServiceImpl'   ,'setStrategy'              ,'1','call pkg_yz_sq_config.p_set(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                              ,'空白凭证印制/凭证申领分配办理/保存策略');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billAlterServiceImpl'   ,'dispsoneBill'             ,'1','call pkg_yz_sq_reply.p_disp(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                              ,'空白凭证印制/凭证申领分配办理/手工分配');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billAlterServiceImpl'   ,'refuseApply'              ,'1','call pkg_yz_sq_reply.p_refuse(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                            ,'空白凭证印制/凭证申领分配办理/申领拒绝');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billAlterServiceImpl'   ,'loadDetailTab'            ,'1','call pkg_yz_sq_reply.p_getpzlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'               ,'空白凭证印制/凭证申领分配办理/打开凭证');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billAlterServiceImpl'   ,'getStatusList'            ,'1','call proc_getsyscode(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                           ,'空白凭证印制/凭证申领分配办理/组合查询状态获取');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billAlterServiceImpl'   ,'finishDisp'               ,'1','call pkg_yz_sq.p_finish(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                  ,'空白凭证印制/凭证申领分配办理/办结');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('certTypeServiceImpl'    ,'querySlDeptPageList'      ,'1','call pkg_yz_sq_com.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                   ,'空白凭证印制/凭证申领分发单位/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('certTypeServiceImpl'    ,'querySelectedSlDept'      ,'1','call pkg_yz_sq_com.p_getcoms(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                   ,'空白凭证印制/凭证申领分发单位/单位增加/已加单位集合');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('certTypeServiceImpl'    ,'operSlDeptInfo'           ,'1','call pkg_yz_sq_com.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                ,'空白凭证印制/凭证申领分发单位/单位增加(删除)');
-- 空白凭证申领  
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('applyFstStatServiceImpl','queryPageList'            ,'1','call pkg_sq_first.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'空白凭证申领/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billApplyServiceImpl'   ,'getSettledDeptInfo'       ,'1','call pkg_sq_dzcom.p_getinfo(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'空白凭证申领/代制单位查询');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('certTypeServiceImpl'    ,'operZzDeptInfo'           ,'1','call pkg_sq_dzcom.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                 ,'空白凭证申领/代制单位设置');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billStockServiceImpl'   ,'queryPageList'            ,'2','call pkg_sq_pz.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_info2, :o_code, :o_msg)'             ,'空白凭证申领/申领空白凭证/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billStockServiceImpl'   ,'getPageOpenInfo'          ,'2','call pkg_sq_pz.p_getinfo(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_info2, :o_code, :o_msg)'             ,'空白凭证申领/申领空白凭证/打开凭证');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billStockServiceImpl'   ,'operCertInfo'             ,'1','call pkg_sq_pz.p_del(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                     ,'空白凭证申领/申领空白凭证/删除');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billApplyServiceImpl'   ,'queryPageList'            ,'1','call pkg_sq_book.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                     ,'空白凭证申领/空白申领办理/列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billApplyServiceImpl'   ,'operApplyInfo'            ,'1','call pkg_sq_book.p_oper(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                        ,'空白凭证申领/空白申领办理/增加(删除)(办结)');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billApplyServiceImpl'   ,'loadDetailTab'            ,'1','call pkg_sq_book_pz.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                  ,'空白凭证申领/空白申领办理/打开凭证');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('billApplyServiceImpl'   ,'getStatusList'            ,'1','call proc_getsyscode(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                           ,'空白凭证申领/空白申领办理/组合查询状态获取');
-- 入账凭证签发办理  
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('CreditedService'        ,'queryPageList'            ,'1','call pkg_qf2_com.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                     ,'入账凭证签发办理/查询单位列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('CreditedService'        ,'setSignProlicy'           ,'1','call pkg_qf2_com.p_upd(:i_forminfo, :i_operuri, :i_opername, :o_code, :o_msg)'                                   ,'入账凭证签发办理/设置签发策略');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('CreditedService'        ,'loadTypeList'             ,'1','call pkg_qf2_task.p_gettype(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'入账凭证签发办理/查询凭证类型');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('CreditedService'        ,'queryProofPageList'       ,'1','call pkg_qf2_task.p_getlist(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'入账凭证签发办理/查询签发列表');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('CreditedService'        ,'getProofOpenData'         ,'1','call pkg_qf2_task.p_getinfo(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'入账凭证签发办理/查询签发文件');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('CreditedService'        ,'deleteProof'              ,'1','call pkg_qf2_task.p_del(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                        ,'入账凭证签发办理/删除签发数据');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('CreditedService'        ,'confirmSignProof'         ,'1','call pkg_qf2_task.p_confirm(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                    ,'入账凭证签发办理/确认签发');
insert into info_deal(beanname,methodname,stype,stmt,remark) VALUES('CreditedService'        ,'refuseSignProof'          ,'1','call pkg_qf2_task.p_refuse(:i_forminfo, :i_operuri, :i_opername, :o_info1, :o_code, :o_msg)'                     ,'入账凭证签发办理/拒绝签发');
commit;
